# Generated by Django 3.1.5 on 2021-01-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='123', max_length=50, verbose_name='Пароль'),
            preserve_default=False,
        ),
    ]
