# Generated by Django 3.1.5 on 2021-01-16 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shops',
            old_name='aditional_type',
            new_name='additional_type',
        ),
    ]
