# Generated by Django 3.1.5 on 2021-01-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_shops_created_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops',
            name='inn',
            field=models.CharField(max_length=20, verbose_name='ИНН'),
        ),
    ]
