# Generated by Django 3.1.5 on 2021-01-19 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210119_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('inn', models.CharField(max_length=20, verbose_name='ИНН')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='Номер телефона')),
                ('district', models.CharField(choices=[('Алтыарыкский район', 'Алтыарыкский район'), ('Багдадский район', 'Багдадский район'), ('Бешарыкский район', 'Бешарыкский район'), ('Бувайдинский район', 'Бувайдинский район'), ('Язъяванский район', 'Язъяванский район'), ('Ферганский район', 'Ферганский район'), ('Дангаринский район', 'Дангаринский район'), ('Фуркатский район', 'Фуркатский район'), ('Куштепинский район', 'Куштепинский район'), ('Кувинский район', 'Кувинский район'), ('Риштанский район', 'Риштанский район'), ('Сохский район', 'Сохский район'), ('Ташлакский район', 'Ташлакский район'), ('Учкуприкский район', 'Учкуприкский район'), ('Узбекистанский район', 'Узбекистанский район')], default='', max_length=100, verbose_name='Район')),
                ('address', models.CharField(max_length=255, verbose_name='Адресс')),
                ('landmark', models.CharField(max_length=255, verbose_name='Ориентир')),
                ('additional_type', models.CharField(blank=True, max_length=50, verbose_name='Другой тип (можете оставить пустым)')),
                ('created_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userprofile')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.DeleteModel(
            name='Shops',
        ),
        migrations.AddField(
            model_name='category',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.shop'),
        ),
    ]
