# Generated by Django 3.1.5 on 2021-01-19 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210119_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='additional_type',
        ),
    ]
