# Generated by Django 3.1.5 on 2021-01-19 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210119_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='additional_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.CharField(choices=[(1, 'category0'), (2, 'category1'), (3, 'category2'), (4, 'category3')], max_length=2, verbose_name='Категория'),
        ),
    ]
