# Generated by Django 3.1.5 on 2021-01-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210119_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='additional_category',
            field=models.CharField(blank=True, max_length=255, verbose_name='Можете оставить пустым, если выбрали категорию сверху'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.CharField(blank=True, choices=[('1', 'category0'), ('2', 'category1'), ('3', 'category2'), ('4', 'category3')], max_length=2, verbose_name='Категория'),
        ),
    ]
