# Generated by Django 3.1.5 on 2021-01-19 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210119_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='created_person',
            new_name='person',
        ),
    ]
