# Generated by Django 3.1.5 on 2021-01-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210119_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.CharField(blank=True, max_length=2, verbose_name='Категория'),
        ),
    ]
