# Generated by Django 3.1.5 on 2021-01-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210119_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Категория'),
        ),
    ]
