# Generated by Django 3.1.5 on 2021-01-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210119_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.CharField(blank=True, choices=[('1', 'category0'), ('2', 'category1'), ('3', 'category2'), ('4', 'category3'), ('5', '')], max_length=100, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='district',
            field=models.CharField(choices=[('1', 'Алтыарыкский район'), ('2', 'Фергана'), ('3', ' Андижан'), ('4', 'Ташкент'), ('5', 'Чирчик'), ('6', ' Кута')], default='', max_length=100, verbose_name='Район'),
        ),
    ]
