# Generated by Django 3.1.5 on 2021-01-19 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0016_auto_20210119_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('category', models.JSONField(verbose_name='Категория')),
                ('price_for_one', models.FloatField(max_length=10, verbose_name='Цена за штуку')),
                ('price_for_wholesaler', models.FloatField(max_length=10, verbose_name='Цена для оптовика')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('min_quantity_to_buy', models.IntegerField(verbose_name='Минимальное количество для покупки')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('photo', models.ImageField(blank=True, upload_to='goods/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.DeleteModel(
            name='Goods',
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'Район', 'verbose_name_plural': 'Районы'},
        ),
        migrations.RemoveField(
            model_name='shop',
            name='additional_category',
        ),
        migrations.AddField(
            model_name='shop',
            name='token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.JSONField(verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='district',
            field=models.JSONField(verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
