# Generated by Django 3.1.5 on 2021-01-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210119_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.CharField(max_length=6, verbose_name='Категория'),
        ),
    ]
