# Generated by Django 3.1.5 on 2021-01-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20210119_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='district',
            field=models.CharField(max_length=6, verbose_name='Район'),
        ),
    ]
