# Generated by Django 3.1.5 on 2021-01-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20210119_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
